# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d89bc98795af4a4c88c7f3a3f2900a370fe584118b848861adb499cb27d53f5b548a85bead05a4eedf1e0d80b2b3c5b22ebc6e96dd5458d4cce0ee099c0b4cef

test:
  secret_key_base: 72e76fdd5904d7885fbb90b8cdbc6a31bfffb9903dbb12faf1f63bcd487bcd1d3cf4255a05a630cafd0d6f0a1555b9b9e89ede1e295945c54aea6e9fc4f7a129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
